### ISSUE TITLE
Command a2nsite doesn't work

### ISSUE THREAD

**Issue by thaxy** [owncloud-docker/php#1]
Hello,

I try to configure my installation with SSL access. The official docs for the non docker repo [state](https://doc.owncloud.org/server/10.0/admin_manual/installation/source_installation.html#enabling-ssl-label) to use the command [a2ensite](https://manpages.debian.org/jessie/apache2/a2dissite.8.en.html), which creates a symlink to a file within ``/etc/apache2/sites-*``. The command throws an error because the directory doesn't exist. That's no surprise since it was deleted as defined in the [Dockerfile](/etc/apache2/sites-*).

Am I missing something? What's the reason for deleting the directories?

The [documentation](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/) for SSL with docker (note the https://localhost) is lacking information and seems to be not complete.
I guess I will modify the ``docker-compose.yml`` by overriding all neccessary files in ``/etc/apache2/sites-enabled``. This directory seems to be somwhere recreated.

**Comment by DeepDiver1975** [comment]
This docker Image is for pure development and CI purpose. Your described scenario does not fit into the scope of this Image.

**Comment by thaxy** [comment]
Mhh, yeah well... I was wondering why the owncloud docker image would delete those directories while on a normal apache installation they are still present. Of course, this repo is for development purposes but as far as I see is the mentioned line of the Dockerfile in this repository responsible for the deletion of those.

My initial confusion came from the recent change of dropping the SSL support in the docker installation and the outdated docs. I have already made an attempt to make it better understandable for others.

Good luck with this project.

**Comment by tboerger** [comment]
> This docker Image is for pure development and CI purpose. Your described scenario does not fit into the scope of this Image.

This image is not meant for CI, but it's tailored to our needs for ownCloud and Wordpress hosting.

We suggest to use a reverse proxy for SSL termination, that's why we have dropped the self-signed cert and SSL stuff from the Docker image. If you really want to customize the webhost you can always overwrite https://github.com/owncloud-docker/php/blob/master/rootfs/etc/apache2/sites-enabled/default.conf with a Docker volume.

For our ownCloud images we are already doing that with the template from https://github.com/owncloud-docker/base/blob/master/rootfs/etc/templates/apache.conf.
